services:
  - type: web
    name: mastering-api
    env: docker
    rootDir: apps/mastering-api
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mastering-db
          property: connectionString
      - key: ALLOWED_ORIGINS
        value: '*'
      - key: MASTERING_CLI_PATH
        value: ''

  - type: web
    name: leads-api
    env: docker
    rootDir: apps/leads-api
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: leads-db
          property: connectionString
      - key: ALLOWED_ORIGINS
        value: '*'
      - key: YT_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: EMAIL_FROM
        value: 'beats@yourdomain.com'
      - key: EMAIL_FROM_NAME
        value: 'Kade'
      - key: EMAIL_RATE_SECONDS
        value: '45'

  - type: web
    name: mastering-ui
    env: node
    rootDir: apps/mastering-ui
    plan: free
    buildCommand: 'npm i && npm run build'
    startCommand: 'npm run start'
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: '20'
      - key: NEXT_PUBLIC_MASTERING_API_URL
        value: ''

  - type: web
    name: leads-ui
    env: node
    rootDir: apps/leads-ui
    plan: free
    buildCommand: 'npm i && npm run build'
    startCommand: 'npm run start'
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: '20'
      - key: NEXT_PUBLIC_LEADS_API_URL
        value: ''

databases:
  - name: mastering-db
    plan: free
  - name: leads-db
    plan: free
